// --- DIZIONARIO PAROLE ---
// Ogni categoria ha le sue coppie: [parola A, parola B]. Chi riceve quale parola è deciso a caso a ogni partita.
export const wordCategories = [
  {
    id: 'cibo',
    label: 'Cibo e bevande',
    emoji: '🍕',
    pairs: [
      ['Pizza', 'Pasta'], ['Hamburger', 'Hotdog'], ['Gelato', 'Sorbetto'], ['Vino', 'Birra'],
      ['Zucchero', 'Sale'], ['Burro', 'Margarina'], ['Caffè', 'Tè'], ['Arancia', 'Mandarino'],
      ['Mela', 'Pera'], ['Biscotto', 'Pasticcino'], ['Pane', 'Focaccia'], ['Sushi', 'Sashimi'],
      ['Ketchup', 'Maionese'], ['Coca Cola', 'Pepsi'], ['Latte', 'Panna'], ['Riso', 'Farro'],
      ['Prosciutto', 'Salame'], ['Parmigiano', 'Pecorino'], ['Pesca', 'Albicocca'], ['Anguria', 'Melone'],
      ['Patatine', 'Popcorn'], ['Torta', 'Crostata'], ['Nutella', 'Marmellata'], ['Acqua', 'Seltz'],
      ['Pollo', 'Tacchino'], ['Salmone', 'Tonno'], ['Lasagna', 'Cannelloni'], ['Miele', 'Sciroppo'],
      ['Limone', 'Lime'], ['Cipolla', 'Aglio'], ['Fragola', 'Lampone'], ['Ciliegia', 'Amarena'],
      ['Speck', 'Pancetta'], ['Uovo', 'Omelette'], ['Yogurt', 'Kefir'], ['Noci', 'Nocciole'],
      ['Mandorle', 'Pistacchi'], ['Cioccolato', 'Cacao'], ['Vaniglia', 'Cannella'], ['Zenzero', 'Curcuma'],
      ['Pepe', 'Peperoncino'], ['Origano', 'Basilico'], ['Prezzemolo', 'Sedano'], ['Carota', 'Zucca'],
      ['Melanzana', 'Zucchina'], ['Patata', 'Topinambur'], ['Broccolo', 'Cavolfiore'], ['Spinaci', 'Bietola'],
      ['Fagioli', 'Lenticchie'], ['Ceci', 'Piselli'], ['Mais', 'Orzo'], ['Olio', 'Aceto'],
      ['Senape', 'Salsa BBQ'], ['Cocktail', 'Mocktail'], ['Spumante', 'Champagne'], ['Grappa', 'Whisky'],
      ['Vodka', 'Gin'], ['Liquore', 'Amaro'], ['Panino', 'Tramezzino'], ['Piadina', 'Kebab'],
      ['Muffin', 'Cupcake'], ['Cheesecake', 'Tiramisù'], ['Crepe', 'Waffle'], ['Couscous', 'Quinoa'],
      ['Tofu', 'Seitan'], ['Sogliola', 'Orata'], ['Gambero', 'Aragosta'], ['Cozze', 'Vongole'],
      ['Polpo', 'Seppia'], ['Tartufo', 'Fungo'], ['Pistacchio', 'Anacardo'], ['Ravioli', 'Tortellini'],
      ['Meringa', 'Panna Montata'], ['Polpetta', 'Salsiccia'], ['Acqua Naturale', 'Acqua Frizzante'],
      ['Bresaola', 'Crudo'], ['Gorgonzola', 'Roquefort'], ['Radicchio', 'Insalata'], ['Finocchio', 'Sedano'],
      ['Carciofo', 'Cardo'], ['Porro', 'Scalogno'], ['Melograno', 'Ribes'], ['Mora', 'Mirtillo'],
      ['Fico', 'Dattero'], ['Prugna', 'Susina'], ['Ananas', 'Mango'], ['Papaya', 'Avocado'],
      ['Lupini', 'Fave'], ['Cecina', 'Farinata'], ['Brioche', 'Cornetto'], ['Babà', 'Sfogliatella'],
      ['Zabaione', 'Crema Pasticcera'], ['Sugo', 'Ragù'], ['Pesto', 'Salsa di Noci'],
      ['Tagliatelle', 'Fettuccine'], ['Gnocchi', 'Tortelli'], ['Focaccia', 'Pizza Bianca'], ['Toast', 'Sandwich'],
      ['Carpaccio', 'Bresaola'], ['Salame', 'Salamella'], ['Wurstel', 'Salsiccia'], ['Faraona', 'Anatra'],
      ['Trota', 'Branzino'], ['Totano', 'Calamaro'], ['Telline', 'Lupini'], ['Mazzancolla', 'Scampo'],
      ['Uovo Sodo', 'Uovo alla Coque'], ['Frittata', 'Tortilla'], ['Crema Catalana', 'Creme Brulée'], ['Budino', 'Mousse'],
      ['Macaron', 'Amaretto'], ['Ciambella', 'Krapfen'], ['Bombolone', 'Pancake'], ['Cannolo', 'Sfogliatella'],
      ['Panettone', 'Pandoro'], ['Colomba', 'Uovo di Pasqua'], ['Castagna', 'Marrone'], ['Pinolo', 'Seme di Girasole'],
      ['Arachide', 'Nocciolina'], ['Confettura', 'Miele'], ['Zucchero a velo', 'Zucchero di canna'], ['Sciroppo d\'acero', 'Agave'],
      ['Salsa Tartara', 'Salsa Rosa'], ['Salsa Verde', 'Chimichurri'], ['Olio d\'oliva', 'Olio di girasole'], ['Aceto di mele', 'Aceto balsamico'],
      ['Lenticchie', 'Fagioli'], ['Asparago', 'Luppolo'], ['Verza', 'Cavolo'], ['Rucola', 'Valeriana'],
      ['Porcino', 'Finferlo'], ['Champignon', 'Prataiolo'], ['Pompelmo', 'Pomelo'], ['Cedro', 'Bergamotto'],
      ['Clementine', 'Mandarini'], ['Fico d\'India', 'Dragon Fruit'], ['Litchi', 'Rambutan'], ['Passito', 'Moscato'],
      ['Sidro', 'Succo di Mela'], ['Granita', 'Sorbetto'], ['Frappé', 'Frullato'], ['Centrifuga', 'Estratto'],
      ['Latte di Mandorla', 'Latte di Soia'], ['Kefir', 'Yogurt Greco'], ['Gorgonzola', 'Taleggio'], ['Fontina', 'Asiago'],
      ['Provola', 'Scamorza'], ['Mozzarella', 'Burrata'], ['Stracciatella', 'Ricotta'], ['Mascarpone', 'Panna'],
      ['Speck', 'Lonza'], ['Mortadella', 'Bologna'], ['Zampone', 'Cotechino'], ['Spezzatino', 'Gulasch'],
      ['Arrosto', 'Brasato'], ['Vitello Tonnato', 'Carpaccio'], ['Insalata Russa', 'Insalata di patate'], ['Baccalà', 'Stoccafisso'],
      ['Cacciucco', 'Zuppa di Pesce'], ['Paella', 'Risotto alla pescatora'], ['Zafferano', 'Curcuma'], ['Curry', 'Paprika'],
      ['Noce Moscata', 'Chiodi di Garofano'], ['Anice Stellato', 'Cumino'], ['Rosmarino', 'Salvia'], ['Timo', 'Maggiorana'],
      ['Menta', 'Eucalipto'], ['Camomilla', 'Tisana'], ['Decotto', 'Infuso'], ['Nocino', 'Limoncello'],
      ['Sambuca', 'Anisetta'], ['Vermouth', 'Martini'], ['Spritz', 'Negroni'], ['Mojito', 'Caipirinha'],
      ['Tacos', 'Burrito'], ['Nachos', 'Tortillas'], ['Guacamole', 'Hummus'], ['Kebab', 'Gyros'],
      ['Gyoza', 'Ravioli cinesi'], ['Ramen', 'Noodles'], ['Tempura', 'Fritto Misto'], ['Falafel', 'Polpette'],
      ['Pancake', 'Waffle'], ['Brownie', 'Muffin'], ['Cheeseburger', 'Hamburger'], ['Hot Dog', 'Corn Dog'],
      ['Carbonara', 'Amatriciana'], ['Spaghetti', 'Bucatini'], ['Penne', 'Fusilli'], ['Minestrone', 'Vellutata'],
      ['Cotoletta', 'Bistecca'], ['Maritozzo', 'Bignè'], ['Pizzetta', 'Calzone'], ['Supplì', 'Arancino'],
      ['Olive', 'Capperi'], ['Pomodoro', 'Peperone'], ['Cetriolo', 'Ravanello'], ['Lecca-lecca', 'Caramella'],
      ['Chewing gum', 'Mentina'], ['Taralli', 'Grissini'], ['Crackers', 'Gallette'], ['Brodo', 'Zuppa'],
      ['Aranciata', 'Limonata'], ['Cappuccino', 'Latte macchiato'], ['Espresso', 'Americano'], ['Succo di frutta', 'Spremuta'],
      ['Merendina', 'Snack'], ['Uva', 'Uvetta'], ['Cocco', 'Banana'], ['Zucchero filato', 'Mela caramellata'],
      ['Barbecue', 'Grigliata'], ['Picnic', 'Pranzo al sacco'], ['Colazione', 'Merenda'], ['Pranzo', 'Cena'],
      ['Aperitivo', 'Apericena']
    ],
  },
  {
    id: 'casa',
    label: 'Casa e oggetti',
    emoji: '🏠',
    pairs: [
      ['Sedia', 'Poltrona'], ['Tavolo', 'Scrivania'], ['Letto', 'Divano'], ['Armadio', 'Cassettiera'],
      ['Lampada', 'Lampadario'], ['Specchio', 'Quadro'], ['Tenda', 'Persiana'], ['Tappeto', 'Moquette'],
      ['Orologio', 'Sveglia'], ['Vaso', 'Cestino'], ['Cuscino', 'Coperta'], ['Padella', 'Pentola'],
      ['Piatto', 'Vassoio'], ['Bicchiere', 'Tazza'], ['Forchetta', 'Cucchiaio'], ['Coltello', 'Forbici'],
      ['Frigorifero', 'Congelatore'], ['Forno', 'Microonde'], ['Lavatrice', 'Asciugatrice'], ['Zaino', 'Valigia'],
      ['Portafoglio', 'Borsello'], ['Ombrello', 'Impermeabile'], ['Chiave', 'Lucchetto'], ['Candela', 'Torcia'],
      ['Sapone', 'Shampoo'], ['Dentifricio', 'Collutorio'], ['Spazzolino', 'Pettine'], ['Asciugamano', 'Accappatoio'],
      ['Quaderno', 'Diario'], ['Penna', 'Matita'], ['Gomma', 'Temperino'], ['Righello', 'Squadra'],
      ['Bottiglia', 'Borraccia'], ['Tappo', 'Sughero'], ['Secchio', 'Mocio'], ['Scopa', 'Aspirapolvere'],
      ['Ferro da stiro', 'Vaporella'], ['Molletta', 'Gruccia'], ['Calamita', 'Adesivo'], ['Cornice', 'Poster'],
      ['Divano', 'Pouf'], ['Scaffale', 'Libreria'], ['Lampadina', 'Faretto'], ['Batteria', 'Pila'],
      ['Telecomando', 'Gamepad'], ['Caricabatterie', 'Powerbank'], ['Portachiavi', 'Moschettone'], ['Accendino', 'Fiammiferi'],
      ['Occhiali', 'Lenti a contatto'], ['Lente d\'ingrandimento', 'Microscopio'], ['Telescopio', 'Binocolo'],
      ['Mappa', 'Bussola'], ['Globo', 'Atlante'], ['Ombrellone', 'Sdraio'], ['Amaca', 'Altalena'],
      ['Ago', 'Spilla'], ['Filo', 'Lana'], ['Bottone', 'Cerniera'], ['Martello', 'Cacciavite'],
      ['Vite', 'Bullone'], ['Chiodo', 'Tassello'], ['Pinza', 'Tenaglia'], ['Sega', 'Trapano'],
      ['Scala', 'Sgabello'], ['Secchio', 'Annaffiatoio'], ['Pala', 'Piccone'], ['Rastrello', 'Vanga'],
      ['Valigia', 'Trolley'], ['Borsone', 'Sacca'], ['Portadocumenti', 'Cartellina'], ['Evidenziatore', 'Pennarello'],
      ['Scotch', 'Colla'], ['Cucitrice', 'Perforatrice'], ['Gaffeur', 'Nastro Isolante'], ['Pennello', 'Rullo'],
      ['Spatola', 'Cazzuola'], ['Livella', 'Metro'], ['Zanzariera', 'Tenda'], ['Radiatore', 'Stufa'],
      ['Ventilatore', 'Condizionatore'], ['Caldaia', 'Boiler'], ['Citofono', 'Campanello'], ['Cassaforte', 'Scrigno'],
      ['Phon', 'Piastra'], ['Rasoio', 'Tagliacapelli'], ['Bilancia', 'Metro'], ['Aspirapolvere', 'Robot'],
      ['Moka', 'Macchina espresso'], ['Tostapane', 'Piastra'], ['Frullatore', 'Mixer'], ['Spremiagrumi', 'Centrifuga'],
      ['Grattugia', 'Mandolina'], ['Scolapasta', 'Colino'], ['Apribottiglie', 'Cavatappi'], ['Presina', 'Guanto da forno'],
      ['Stoviglie', 'Posate'], ['Tovaglia', 'Runner'], ['Tovagliolo', 'Fazzoletto'], ['Cestino', 'Secchio'],
      ['Divisorio', 'Paravento'], ['Comodino', 'Consolle'], ['Sgabello', 'Panca'], ['Appendiabiti', 'Stendiabiti'],
      ['Zerbino', 'Tappetino'], ['Serratura', 'Lucchetto'], ['Pomello', 'Maniglia'], ['Cerniera', 'Cardine'],
      ['Cavo', 'Filo'], ['Presa', 'Interruttore'], ['Multipresa', 'Adattatore'], ['Lampada da terra', 'Abat-jour'],
      ['Culla', 'Lettino'], ['Box', 'Seggiolone'], ['Passeggino', 'Carrozzina'], ['Fasciatoio', 'Vaschetta'],
      ['Attenti al cane', 'Campanello'], ['Buca delle lettere', 'Citofono'], ['Gancio', 'Ventosa'], ['Tassello', 'Vite'],
      ['Carta igienica', 'Rotolone'], ['Spugna', 'Luffa'], ['Pumice', 'Lima'], ['Pennello trucco', 'Spugnetta'],
      ['Ombretto', 'Fard'], ['Mascara', 'Eyeliner'], ['Rossetto', 'Lucidalabbra'], ['Fondotinta', 'Correttore'],
      ['Crema viso', 'Siero'], ['Maschera', 'Fango'], ['Ceretta', 'Rasoio'], ['Pinzetta', 'Forbicina'],
      ['Bigodino', 'Molletta'], ['Elastico', 'Cerchietto'], ['Fermaglio', 'Spilla'], ['Parrucca', 'Extension'],
      ['Valvola', 'Rubinetto'], ['Sifone', 'Scarico'], ['Guarnizione', 'O-ring'], ['Tubo', 'Flessibile'],
      ['Finestra', 'Porta'], ['Balcone', 'Terrazzo'], ['Cantina', 'Soffitta'], ['Garage', 'Posto auto'],
      ['Vasca', 'Doccia'], ['Lavandino', 'Bidet'], ['Cucina', 'Salotto'], ['Camera da letto', 'Cameretta'],
      ['Lenzuolo', 'Piumone'], ['Materasso', 'Brandina'], ['Busta', 'Sacchetto'], ['Scatola', 'Cassetta'],
      ['Barattolo', 'Vasetto'], ['Radio', 'Giradischi'], ['Libro', 'Rivista'], ['Giornale', 'Volantino'],
      ['Lettera', 'Cartolina'], ['Francobollo', 'Timbro'], ['Candeggina', 'Detersivo'], ['Termosifone', 'Camino']
    ],
  },
  {
    id: 'natura',
    label: 'Animali, natura e spazio',
    emoji: '🐾',
    pairs: [
      ['Gatto', 'Cane'], ['Leone', 'Tigre'], ['Lupo', 'Volpe'], ['Elefante', 'Ippopotamo'],
      ['Delfino', 'Balena'], ['Squalo', 'Orca'], ['Aquila', 'Falco'], ['Pappagallo', 'Canarino'],
      ['Serpente', 'Lucertola'], ['Rana', 'Rospo'], ['Ape', 'Vespa'], ['Farfalla', 'Falena'],
      ['Sole', 'Luna'], ['Stella', 'Pianeta'], ['Mare', 'Oceano'], ['Fiume', 'Torrente'],
      ['Montagna', 'Collina'], ['Bosco', 'Foresta'], ['Prato', 'Giungla'], ['Deserto', 'Savana'],
      ['Pioggia', 'Grandine'], ['Vento', 'Brezza'], ['Tuono', 'Fulmine'], ['Albero', 'Arbusto'],
      ['Rosa', 'Tulipano'], ['Erba', 'Muschio'], ['Sabbia', 'Ghiaia'], ['Giraffa', 'Zebra'],
      ['Gorilla', 'Scimpanzé'], ['Orso', 'Panda'], ['Canguro', 'Koala'], ['Cammello', 'Dromedario'],
      ['Mucca', 'Toro'], ['Pecora', 'Capra'], ['Maiale', 'Cinghiale'], ['Coniglio', 'Lepre'],
      ['Topo', 'Hamster'], ['Pipistrello', 'Vampiro'], ['Formica', 'Termite'], ['Ragno', 'Scorpione'],
      ['Lumaca', 'Verme'], ['Medusa', 'Corallo'], ['Stella marina', 'Riccio di mare'], ['Granchio', 'Aragosta'],
      ['Ostrica', 'Cozza'], ['Vulcano', 'Geyser'], ['Isola', 'Atollo'], ['Grotta', 'Anfratto'],
      ['Cascata', 'Rapida'], ['Cielo', 'Atmosfera'], ['Nuvola', 'Nebbia'], ['Aurora', 'Arcobaleno'],
      ['Eclissi', 'Cometa'], ['Quercia', 'Faggio'], ['Ulivo', 'Pino'], ['Margherita', 'Girasole'],
      ['Orchidea', 'Giglio'], ['Cactus', 'Pianta Grassa'], ['Ghiacciaio', 'Iceberg'], ['Stagno', 'Palude'],
      ['Duna', 'Spiaggia'], ['Scogliera', 'Rupo'], ['Piuma', 'Pelo'], ['Ala', 'Pinna'],
      ['Corno', 'Zanna'], ['Nido', 'Tana'], ['Guscio', 'Corazza'], ['Coda', 'Zampa'],
      ['Fulmine', 'Saetta'], ['Tramonto', 'Alba'], ['Fango', 'Argilla'], ['Pietra', 'Sasso'],
      ['Radice', 'Ramo'], ['Foglia', 'Petalo'], ['Seme', 'Frutto'], ['Polline', 'Nettare'],
      ['Cervo', 'Capriolo'], ['Gufo', 'Civetta'], ['Corvo', 'Gazza'], ['Passero', 'Pettirosso'],
      ['Cigno', 'Anatra'], ['Fenicottero', 'Airone'], ['Pinguino', 'Foca'], ['Tricheco', 'Lontra'],
      ['Alce', 'Renna'], ['Bisonte', 'Bufalo'], ['Leopardo', 'Ghepardo'], ['Iena', 'Sciacallo'],
      ['Lemure', 'Bradipo'], ['Talpa', 'Riccio'], ['Castoro', 'Lontra'], ['Procione', 'Tasso'],
      ['Scoiattolo', 'Ghiro'], ['Criceto', 'Porcellino d\'india'], ['Pavone', 'Fagiano'], ['Gallo', 'Tacchino'],
      ['Gallina', 'Pulcino'], ['Oca', 'Cigno'], ['Colibrì', 'Farfalla'], ['Pipistrello', 'Civetta'],
      ['Salamandra', 'Tritone'], ['Tartaruga', 'Testuggine'], ['Coccodrillo', 'Alligatore'], ['Camaleonte', 'Iguana'],
      ['Polpo', 'Seppia'], ['Medusa', 'Caravella Portoghese'], ['Cavalluccio Marino', 'Dragone Foglia'], ['Manta', 'Razza'],
      ['Barracuda', 'Luccio'], ['Trota', 'Salmone'], ['Storione', 'Pesce Spada'], ['Anguilla', 'Murena'],
      ['Grillo', 'Cavalletta'], ['Coccinella', 'Scarabeo'], ['Mantide', 'Stecco'], ['Mosca', 'Zanzara'],
      ['Libellula', 'Farfalla'], ['Cicala', 'Grillo'], ['Scarafaggio', 'Cimice'], ['Acaro', 'Pidocchio'],
      ['Felce', 'Lichene'], ['Funghi', 'Muffa'], ['Edera', 'Vite'], ['Baobab', 'Sequoia'],
      ['Salice Piangente', 'Betulla'], ['Abete', 'Larice'], ['Magnolia', 'Mimosa'], ['Lavanda', 'Rosmarino'],
      ['Grano', 'Mais'], ['Riso', 'Bambù'], ['Canna da zucchero', 'Papiro'], ['Nenufar', 'Loto'],
      ['Gelsomino', 'Gardenia'], ['Garofano', 'Peonia'], ['Papavero', 'Anemone'], ['Iris', 'Violetta'],
      ['Ortensia', 'Camelia'], ['Azalea', 'Rododendro'], ['Ginestra', 'Mimosa'], ['Oleandro', 'Alloro'],
      ['Astronauta', 'Cosmonauta'], ['Galassia', 'Nebulosa'], ['Pianeta', 'Asteroide'], ['Sole', 'Stella nana'],
      ['Microscopio', 'Telescopio'], ['Atomo', 'Molecola'], ['Laboratorio', 'Osservatorio'], ['Razzo', 'Navetta'],
      ['Gravità', 'Magnetismo'], ['Elettricità', 'Energia Solare'],
      ['Cavallo', 'Asino'], ['Pony', 'Unicorno'], ['Pesce rosso', 'Pesce palla'], ['Gattino', 'Cucciolo'],
      ['Rinoceronte', 'Triceratopo'], ['Dinosauro', 'Drago'], ['Tirannosauro', 'Velociraptor'], ['Struzzo', 'Emù'],
      ['Neve', 'Ghiaccio'], ['Temporale', 'Uragano'], ['Terremoto', 'Tsunami'], ['Onda', 'Marea'],
      ['Conchiglia', 'Perla'], ['Fiore', 'Pianta'], ['Fuochi d\'artificio', 'Petardo'], ['Primavera', 'Autunno'],
      ['Mattina', 'Pomeriggio'], ['Notte', 'Sera']
    ],
  },
  {
    id: 'luoghi',
    label: 'Luoghi e viaggi',
    emoji: '🗺️',
    pairs: [
      ['Roma', 'Parigi'], ['Londra', 'Berlino'], ['New York', 'Los Angeles'], ['Italia', 'Spagna'],
      ['Scuola', 'Liceo'], ['Ufficio', 'Studio'], ['Ospedale', 'Clinica'], ['Farmacia', 'Erboristeria'],
      ['Negozio', 'Boutique'], ['Supermercato', 'Mercato'], ['Bar', 'Caffetteria'], ['Ristorante', 'Trattoria'],
      ['Hotel', 'Pensione'], ['Ostello', 'Campeggio'], ['Spiaggia', 'Lido'], ['Piscina', 'Parco Acquatico'],
      ['Stazione', 'Fermata'], ['Aeroporto', 'Eliporto'], ['Treno', 'Metropolitana'], ['Aereo', 'Jet'],
      ['Autobus', 'Pullman'], ['Tram', 'Filobus'], ['Macchina', 'SUV'], ['Moto', 'Scooter'],
      ['Bicicletta', 'Tandem'], ['Nave', 'Yacht'], ['Traghetto', 'Motonave'], ['Piazza', 'Corso'],
      ['Via', 'Vicolo'], ['Parco', 'Villa'], ['Giardino', 'Orto'], ['Museo', 'Pinacoteca'],
      ['Galleria', 'Esposizione'], ['Chiesa', 'Basilica'], ['Cattedrale', 'Duomo'], ['Stadio', 'Arena'],
      ['Palestra', 'Centro Sportivo'], ['Castello', 'Fortezza'], ['Torre', 'Campanile'], ['Fara', 'Lanterna'],
      ['Ponte', 'Viadotto'], ['Galleria', 'Tunnel'], ['Porto', 'Molo'], ['Venezia', 'Amsterdam'],
      ['Napoli', 'Marsiglia'], ['Madrid', 'Lisbona'], ['Stati Uniti', 'Canada'], ['Cina', 'Giappone'],
      ['Brasile', 'Messico'], ['Australia', 'Sudafrica'], ['Egitto', 'Grecia'], ['Svizzera', 'Austria'],
      ['Banca', 'Sportello'], ['Posta', 'Corriere'], ['Cinema', 'Sala'], ['Teatro', 'Palcoscenico'],
      ['Discoteca', 'Club'], ['Pub', 'Birreria'], ['Biblioteca', 'Libreria'], ['Cimitero', 'Mausoleo'],
      ['Prigione', 'Cella'], ['Tribunale', 'Municipio'], ['Fattoria', 'Cascina'], ['Stalla', 'Recinto'],
      ['Grattacielo', 'Torre'], ['Baita', 'Chalet'], ['Rifugio', 'Bivacco'], ['Luna Park', 'Giostra'],
      ['Zoo', 'Safari'], ['Acquario', 'Delfinario'], ['Planetario', 'Osservatorio'], ['Fiera', 'Sagra'],
      ['Laboratorio', 'Officina'], ['Cantiere', 'Scavo'], ['Taxi', 'Navetta'], ['Camper', 'Roulotte'],
      ['Canoa', 'Kayak'], ['Gondola', 'Piatta'], ['Sottomarino', 'Sommergibile'], ['Mongolfiera', 'Aliante'],
      ['Milano', 'Torino'], ['Firenze', 'Siena'], ['Bologna', 'Modena'], ['Genova', 'Trieste'],
      ['Palermo', 'Catania'], ['Bari', 'Lecce'], ['Verona', 'Padova'], ['Venezia', 'Chioggia'],
      ['Sardegna', 'Sicilia'], ['Corsica', 'Elba'], ['Ischia', 'Capri'], ['Ponza', 'Ventotene'],
      ['Portofino', 'Saint-Tropez'], ['Ibiza', 'Formentera'], ['Mykonos', 'Santorini'], ['Bali', 'Phuket'],
      ['Maldives', 'Seychelles'], ['Sahara', 'Gobi'], ['Amazzonia', 'Congo'], ['Everest', 'K2'],
      ['Alpi', 'Pirenei'], ['Appennini', 'Ande'], ['Nilo', 'Rio delle Amazzoni'], ['Danubio', 'Po'],
      ['Garda', 'Como'], ['Maggiore', 'Trasimeno'], ['Bottega', 'Atelier'], ['Chiosco', 'Edicola'],
      ['Lavanderia', 'Tintoria'], ['Sartoria', 'Calzoleria'], ['Ferramenta', 'Brico'], ['Vivaio', 'Fioraio'],
      ['Edicola', 'Tabaccaio'], ['Pasticceria', 'Panetteria'], ['Macelleria', 'Pescheria'], ['Enoteca', 'Birreria'],
      ['Casinò', 'Bingo'], ['Bowling', 'Sala Giochi'], ['Kartodromo', 'Autodromo'], ['Maneggio', 'Ippodromo'],
      ['Palazzetto', 'Velodromo'], ['Pista di ghiaccio', 'Skate park'], ['Muro di arrampicata', 'Boulder'], ['Parco Avventura', 'Zipline'],
      ['Montagne russe', 'Autoscontro'], ['Parco giochi', 'Oratorio'], ['Asilo', 'Scuola elementare'], ['Università', 'Accademia'],
      ['Mensa', 'Self-service'], ['Pizzeria', 'Paninoteca'], ['Gelateria', 'Yogurteria'], ['Autogrill', 'Benzinaio'],
      ['Autostrada', 'Superstrada'], ['Rotonda', 'Semaforo'], ['Marciapiede', 'Strisce pedonali'], ['Ascensore', 'Scala mobile'],
      ['Centro commerciale', 'Outlet'], ['Spa', 'Terme'], ['Sauna', 'Bagno turco'], ['Barbiere', 'Parrucchiere'],
      ['Canile', 'Gattile'],
      ['Monopattino', 'Hoverboard'], ['Trattore', 'Ruspa'], ['Camion', 'Furgone'], ['Elicottero', 'Idrovolante'],
      ['Funivia', 'Seggiovia'], ['Motoscafo', 'Gommone'], ['Pedalò', 'Canotto'], ['Frecciarossa', 'Italo']
    ],
  },
  {
    id: 'persone',
    label: 'Mestieri e personaggi',
    emoji: '🦸',
    pairs: [
      ['Medico', 'Infermiere'], ['Avvocato', 'Giudice'], ['Poliziotto', 'Carabiniere'], ['Insegnante', 'Professore'],
      ['Cuoco', 'Pasticciere'], ['Muratore', 'Falegname'], ['Idraulico', 'Elettricista'], ['Attore', 'Regista'],
      ['Cantante', 'Musicista'], ['Giornalista', 'Scrittore'], ['Architetto', 'Ingegnere'], ['Barista', 'Cameriere'],
      ['Sartoria', 'Stilista'], ['Pilota', 'Hostess'], ['Autista', 'Tassista'], ['Dentista', 'Igienista'],
      ['Psicologo', 'Psichiatra'], ['Farmacista', 'Erborista'], ['Fotografo', 'Cameraman'], ['Sindaco', 'Presidente'],
      ['Veterinario', 'Pediatra'], ['Pompiere', 'Vigile'], ['Postino', 'Fattorino'], ['Contadino', 'Allevatore'],
      ['Pescatore', 'Marinaio'], ['Pirata', 'Corsaro'], ['Cavaliere', 'Guerriero'], ['Ninja', 'Samurai'],
      ['Re', 'Imperatore'], ['Regina', 'Principessa'], ['Principe', 'Conte'], ['Strega', 'Fata'],
      ['Mago', 'Stregone'], ['Fantasma', 'Spirito'], ['Zombie', 'Mummia'], ['Babbo Natale', 'Befana'],
      ['Elfo', 'Folletto'], ['Batman', 'Superman'], ['Spiderman', 'Iron Man'], ['Topolino', 'Paperino'],
      ['Cenerentola', 'Biancaneve'], ['Pinocchio', 'Peter Pan'], ['Shrek', 'Madagascar']
    ],
  },
  {
    id: 'arte',
    label: 'Arte, musica e spettacolo',
    emoji: '🎬',
    pairs: [
      ['Pittura', 'Scultura'], ['Fumetto', 'Manga'], ['Romanzo', 'Poesia'], ['Commedia', 'Tragedia'],
      ['Film', 'Serie TV'], ['Documentario', 'Reportage'], ['Fotografia', 'Ritratto'], ['Chitarra', 'Basso'],
      ['Pianoforte', 'Tastiera (musicale)'], ['Batteria', 'Percussioni'], ['Flauto', 'Clarinetto'], ['Violino', 'Violoncello'],
      ['Teatro', 'Cinema'], ['Concerto', 'Festival'], ['Museo', 'Mostra'], ['Acrobata', 'Giocoliere'],
      ['Magia', 'Illusionismo'], ['Anime', 'Cartone Animato'], ['Podcast', 'Programma Radio'], ['DJ', 'Vocalist'],
      ['Tromba', 'Trombone'], ['Ukulele', 'Mandolino'], ['Microfono', 'Altoparlante'], ['Rap', 'Trap'],
      ['Rock', 'Metal'], ['Opera', 'Musical'], ['Valzer', 'Tango'], ['Pastelli', 'Acquerelli']
    ],
  },
  {
    id: 'tech',
    label: 'Tecnologia e pop',
    emoji: '📱',
    pairs: [
      ['Smartphone', 'Tablet'], ['Computer', 'Portatile'], ['Mouse', 'Tastiera'], ['Monitor', 'Televisore'],
      ['Auricolari', 'Cuffie'], ['Smartwatch', 'Contapassi'], ['Router', 'Modem'], ['Chiavetta USB', 'Hard Disk'],
      ['Stampante', 'Scanner'], ['Console', 'PC Gaming'], ['Wi-Fi', 'Bluetooth'], ['App', 'Sito Web'],
      ['Social Network', 'Forum'], ['Videogioco', 'Film Interattivo'], ['Drone', 'Elicottero Radiocomandato'],
      ['Cavo HDMI', 'Cavo USB'], ['Password', 'PIN'], ['Antivirus', 'Firewall'], ['Intelligenza Artificiale', 'Algoritmo'],
      ['Harry Potter', 'Il Signore degli Anelli'], ['Pokémon', 'Digimon'], ['Super Mario', 'Sonic'], ['Minecraft', 'Fortnite'],
      ['PlayStation', 'Xbox'], ['Netflix', 'Prime Video'], ['Instagram', 'TikTok'], ['WhatsApp', 'Telegram'],
      ['Google', 'Wikipedia'], ['Emoji', 'Sticker'], ['Selfie', 'Foto di gruppo'], ['Messaggio', 'Email'],
      ['Videochiamata', 'Telefonata'], ['Disney', 'Pixar'], ['Sanremo', 'Eurovision']
    ],
  },
  {
    id: 'giochi',
    label: 'Giochi ed eventi',
    emoji: '🎲',
    pairs: [
      ['Palla', 'Pallone'], ['Bambola', 'Peluche'], ['Puzzle', 'Cruciverba'], ['Aquilone', 'Palloncino'],
      ['Trottola', 'Yo-yo'], ['Biglia', 'Pallina'], ['Nascondino', 'Acchiapparella'], ['Briscola', 'Scala quaranta'],
      ['Tombola', 'Lotteria'], ['Gratta e vinci', 'Lotto'], ['Cluedo', 'Risiko'], ['Jenga', 'Domino'],
      ['Compleanno', 'Anniversario'], ['Matrimonio', 'Battesimo'], ['Festa a sorpresa', 'Addio al celibato'], ['Carnevale', 'Halloween'],
      ['Capodanno', 'Ferragosto'], ['Pasqua', 'Pasquetta'], ['Gita', 'Escursione'], ['Crociera', 'Villaggio turistico'],
      ['Esame', 'Interrogazione'], ['Compito', 'Verifica'], ['Colloquio', 'Riunione'], ['Sciopero', 'Manifestazione'],
      ['Karaoke', 'Talent show']
    ],
  },
  {
    id: 'varie',
    label: 'Sport, vestiti e varie',
    emoji: '👕',
    pairs: [
      ['Maglietta', 'Polo'], ['Camicia', 'Blusa'], ['Pantaloni', 'Jeans'], ['Gonna', 'Tubino'],
      ['Vestito', 'Tuta'], ['Giacca', 'Blazer'], ['Cappotto', 'Piumino'], ['Scarpe', 'Sneakers'],
      ['Stivali', 'Anfibi'], ['Sandali', 'Zoccoli'], ['Infradito', 'Ciabatte'], ['Calze', 'Gambaletti'],
      ['Cappello', 'Berretto'], ['Guanti', 'Manopole'], ['Sciarpa', 'Scaldacollo'], ['Cintura', 'Bretelle'],
      ['Occhiali da sole', 'Mascherina'], ['Orologio', 'Cronometro'], ['Collana', 'Catenina'], ['Anello', 'Fede'],
      ['Orecchini', 'Pendenti'], ['Zaino', 'Cartella'], ['Borsa', 'Tracolla'], ['Portafoglio', 'Portamonete'],
      ['Pigiama', 'Camicia da notte'], ['Calcio', 'Calcetto'], ['Basket', 'Pallavolo'], ['Tennis', 'Squash'],
      ['Nuoto', 'Pallanuoto'], ['Corsa', 'Jogging'], ['Ciclismo', 'Spinning'], ['Sci', 'Slittino'],
      ['Boxe', 'Kickboxing'], ['Danza', 'Ginnastica'], ['Scacchi', 'Dama'], ['Carte', 'Tarocchi'],
      ['Dadi', 'fiches'], ['Yoga', 'Pilates'], ['Rugby', 'Football'], ['Baseball', 'Softball'],
      ['Scherma', 'Fioretto'], ['Vela', 'Surf'], ['Biliardo', 'Bowling'], ['Ping Pong', 'Badminton'],
      ['Pesca', 'Sub'], ['Freccette', 'Tiro a segno'], ['Monopoli', 'Taboo'], ['Lego', 'Costruzioni'],
      ['Medicina', 'Sciroppo'], ['Vitamina', 'Pillola'], ['Febbre', 'Influenza'], ['Raffindigodore', 'Allergia'],
      ['Cerotto', 'Gaza'], ['Termometro', 'Sonda'], ['Cuore', 'Polso'], ['Cervello', 'Mente'],
      ['Dente', 'Molare'], ['Naso', 'Narice'], ['Occhio', 'Pupilla'], ['Sogno', 'Desiderio'],
      ['Incubo', 'Paura'], ['Amore', 'Passione'], ['Amicizia', 'Lealtà'], ['Caldo', 'Afa'],
      ['Findigodo', 'Gelo'], ['Estate', 'Vacanze'], ['Inverno', 'Natale'], ['Musica', 'Canzone'],
      ['Profumo', 'Essenza'], ['Luce', 'Bagliore'], ['Colore', 'Tonalità'], ['Matematica', 'Algebra'],
      ['Storia', 'Leggenda'], ['Veloce', 'Rapido'], ['Lento', 'Pigro'], ['Bello', 'Elegante'],
      ['Nuovo', 'Moderno'], ['Pieno', 'Colmo'], ['Dolce', 'Zuccherato'], ['Morbido', 'Soffice'],
      ['Silenzio', 'Quiete'], ['Vittoria', 'Trionfo'], ['Regalo', 'Dono'], ['Inizio', 'Partenza'],
      ['Felpa', 'Maglione'], ['Cardigan', 'Gilet'], ['Canottiera', 'Top'], ['Bermuda', 'Pantaloncini'],
      ['Calzettoni', 'Fantasmini'], ['Cravatta', 'Papillon'], ['Gemelli', 'Spilla da balia'], ['Fazzoletto', 'Bandana'],
      ['Pantofole', 'Babbucce'], ['Mocassini', 'Scarpe da barca'], ['Tacchi', 'Zeppe'], ['Ballerine', 'Décolleté'],
      ['Cappa', 'Mantello'], ['Poncho', 'Sciarpa oversize'], ['Tuta spaziale', 'Scafandro'], ['Sottoveste', 'Sottogonna'],
      ['Corpetto', 'Corsetto'], ['Reggiseno', 'Bustino'], ['Body', 'Costume intero'], ['Bikini', 'Triangolo'],
      ['Parastinchi', 'Ginocchiere'], ['Casco', 'Elmetto'], ['Borraccia', 'Thermos'], ['Cronometro', 'Timer'],
      ['Fischietto', 'Sirena'], ['Medaglia', 'Coppa'], ['Trofeo', 'Targa'], ['Podio', 'Tribuna'],
      ['Arrampicata', 'Alpinismo'], ['Trekking', 'Escursionismo'], ['Canottaggio', 'Canoa'], ['Tiro con l\'arco', 'Balestra'],
      ['Golf', 'Minigolf'], ['Pattinaggio', 'Hockey'], ['Curling', 'Bocce'], ['Motocross', 'Rally'],
      ['F1', 'MotoGP'], ['Surf', 'Skateboard'], ['Snowboard', 'Skiboard'], ['Paracadutismo', 'Bungee jumping'],
      ['Yoga', 'Tai Chi'], ['Meditazione', 'Rilassamento'], ['Massaggio', 'Fisioterapia'], ['Agopuntura', 'Digitopressione'],
      ['Farmaco', 'Rimedio'], ['Vaccino', 'Antidoto'], ['Benda', 'Fascia'], ['Garza', 'Tampone'],
      ['Ambulanza', 'Auto medica'], ['Lettiga', 'Barella'], ['Sedia a rotelle', 'Deambulatore'], ['Stampelle', 'Tutore'],
      ['Omeopatia', 'Fitoterapia'], ['Erboristeria', 'Spezeria'], ['Stetoscopio', 'Sfigmomanometro'], ['Scalpello', 'Bisturi'],
      ['Paziente', 'Degente'], ['Ricovero', 'Check-up'], ['Analisi', 'Radiografia'], ['Ecografia', 'Risonanza'],
      ['Anestesia', 'Sedazione'], ['Gesso', 'Fasciatura'], ['Sutura', 'Punti'], ['Cicatrizzante', 'Disinfettante'],
      ['Fatica', 'Stanchezza'], ['Energia', 'Vigore'], ['Sonno', 'Riposo'], ['Veglia', 'Insonnia'],
      ['Fame', 'Appetito'], ['Sete', 'Aridità'], ['Salute', 'Benessere'], ['Forma', 'Profilo'],
      ['Peso', 'Massa'], ['Altezza', 'Statura'], ['Forza', 'Potenza'], ['Velocità', 'Rapidità'],
      ['Riflessi', 'Istinto'], ['Talento', 'Genio'], ['Abilità', 'Maestria'], ['Impegno', 'Sforzo'],
      ['Speranza', 'Illusione'], ['Paura', 'Terrore'], ['Gioia', 'Felicità'], ['Tristezza', 'Malinconia'],
      ['Rabbia', 'Frustrazione'], ['Coraggio', 'Temerarietà'], ['Intelligenza', 'Saggezza'], ['Bellezza', 'Fascino'],
      ['Ricchezza', 'Lusso'], ['Povertà', 'Miseria'], ['Destino', 'Fato'], ['Fortuna', 'Caso'],
      ['Sogno', 'Obiettivo'], ['Ricordo', 'Nostalgia'], ['Amore', 'Infatuazione'], ['Simpatia', 'Empatia'],
      ['Portiere', 'Difensore'], ['Arbitro', 'Allenatore'], ['Rigore', 'Punizione'], ['Gol', 'Canestro'],
      ['Inter', 'Milan'], ['Maratona', 'Staffetta'], ['Olimpiadi', 'Mondiali'], ['Tuffo', 'Capriola'],
      ['Mano', 'Piede'], ['Ginocchio', 'Gomito'], ['Capelli', 'Barba'], ['Baffi', 'Pizzetto'],
      ['Sorriso', 'Risata'], ['Lacrima', 'Sudore'], ['Starnuto', 'Tosse'], ['Singhiozzo', 'Sbadiglio'],
      ['Bacio', 'Abbraccio'], ['Tatuaggio', 'Piercing'], ['Lentiggini', 'Nei']
    ],
  },
];
